/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ihebwindow (void)
{
  GtkWidget *ihebwindow;
  GtkWidget *fixed1;
  GtkWidget *treeviewnk;
  GtkWidget *entrychercheriheb;
  GtkWidget *Accueil_iheb_nav;
  GtkWidget *alignment59;
  GtkWidget *hbox59;
  GtkWidget *image72;
  GtkWidget *label176;
  GtkWidget *btn_chercher_iheb;
  GtkWidget *alignment55;
  GtkWidget *hbox55;
  GtkWidget *image55;
  GtkWidget *label164;
  GtkWidget *label174;
  GtkWidget *label177;
  GtkWidget *btn_ajout_iheb;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *btn_modifier_iheb_nav;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *btn_supprimer_iheb;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *btn_reservation_iheb_nav;
  GtkWidget *alignment58;
  GtkWidget *hbox58;
  GtkWidget *image71;
  GtkWidget *label175;
  GtkWidget *btn_actualise;
  GtkWidget *alignment62;
  GtkWidget *hbox62;
  GtkWidget *image75;
  GtkWidget *label194;
  GtkObject *spinbutton_fonction_agent_kh_adj;
  GtkWidget *spinbutton_fonction_agent_kh;
  GtkWidget *type_tarif_label_kh;
  GtkWidget *afficher_par_fonction_kh_button;
  GtkWidget *alignment63;
  GtkWidget *hbox63;
  GtkWidget *image76;
  GtkWidget *label197;
  GtkWidget *non_trouve_label_home;

  ihebwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ihebwindow), _("ihebwindow"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ihebwindow), fixed1);
  gtk_widget_set_size_request (fixed1, 800, 600);

  treeviewnk = gtk_tree_view_new ();
  gtk_widget_show (treeviewnk);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewnk, 56, 128);
  gtk_widget_set_size_request (treeviewnk, 592, 240);

  entrychercheriheb = gtk_entry_new ();
  gtk_widget_show (entrychercheriheb);
  gtk_fixed_put (GTK_FIXED (fixed1), entrychercheriheb, 480, 80);
  gtk_widget_set_size_request (entrychercheriheb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrychercheriheb), 8226);

  Accueil_iheb_nav = gtk_button_new ();
  gtk_widget_show (Accueil_iheb_nav);
  gtk_fixed_put (GTK_FIXED (fixed1), Accueil_iheb_nav, 0, 0);
  gtk_widget_set_size_request (Accueil_iheb_nav, 150, 30);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (Accueil_iheb_nav), alignment59);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox59);

  image72 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image72);
  gtk_box_pack_start (GTK_BOX (hbox59), image72, FALSE, FALSE, 0);

  label176 = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label176);
  gtk_box_pack_start (GTK_BOX (hbox59), label176, FALSE, FALSE, 0);

  btn_chercher_iheb = gtk_button_new ();
  gtk_widget_show (btn_chercher_iheb);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_chercher_iheb, 640, 80);
  gtk_widget_set_size_request (btn_chercher_iheb, 150, 29);

  alignment55 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (btn_chercher_iheb), alignment55);

  hbox55 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox55);
  gtk_container_add (GTK_CONTAINER (alignment55), hbox55);

  image55 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox55), image55, FALSE, FALSE, 0);

  label164 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label164);
  gtk_box_pack_start (GTK_BOX (hbox55), label164, FALSE, FALSE, 0);

  label174 = gtk_label_new (_("<span ><b> ID : </b></span>"));
  gtk_widget_show (label174);
  gtk_fixed_put (GTK_FIXED (fixed1), label174, 424, 80);
  gtk_widget_set_size_request (label174, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (label174), TRUE);

  label177 = gtk_label_new (_("Afficher liste des agents "));
  gtk_widget_show (label177);
  gtk_fixed_put (GTK_FIXED (fixed1), label177, 136, 40);
  gtk_widget_set_size_request (label177, 232, 112);

  btn_ajout_iheb = gtk_button_new ();
  gtk_widget_show (btn_ajout_iheb);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_ajout_iheb, 136, 376);
  gtk_widget_set_size_request (btn_ajout_iheb, 140, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_ajout_iheb), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  btn_modifier_iheb_nav = gtk_button_new ();
  gtk_widget_show (btn_modifier_iheb_nav);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_modifier_iheb_nav, 136, 424);
  gtk_widget_set_size_request (btn_modifier_iheb_nav, 140, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_modifier_iheb_nav), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  btn_supprimer_iheb = gtk_button_new ();
  gtk_widget_show (btn_supprimer_iheb);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_supprimer_iheb, 448, 376);
  gtk_widget_set_size_request (btn_supprimer_iheb, 140, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_supprimer_iheb), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  btn_reservation_iheb_nav = gtk_button_new ();
  gtk_widget_show (btn_reservation_iheb_nav);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_reservation_iheb_nav, 447, 424);
  gtk_widget_set_size_request (btn_reservation_iheb_nav, 140, 32);

  alignment58 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment58);
  gtk_container_add (GTK_CONTAINER (btn_reservation_iheb_nav), alignment58);

  hbox58 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox58);
  gtk_container_add (GTK_CONTAINER (alignment58), hbox58);

  image71 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image71);
  gtk_box_pack_start (GTK_BOX (hbox58), image71, FALSE, FALSE, 0);

  label175 = gtk_label_new_with_mnemonic (_("Reservations"));
  gtk_widget_show (label175);
  gtk_box_pack_start (GTK_BOX (hbox58), label175, FALSE, FALSE, 0);

  btn_actualise = gtk_button_new ();
  gtk_widget_show (btn_actualise);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_actualise, 664, 232);
  gtk_widget_set_size_request (btn_actualise, 120, 30);

  alignment62 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment62);
  gtk_container_add (GTK_CONTAINER (btn_actualise), alignment62);

  hbox62 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox62);
  gtk_container_add (GTK_CONTAINER (alignment62), hbox62);

  image75 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image75);
  gtk_box_pack_start (GTK_BOX (hbox62), image75, FALSE, FALSE, 0);

  label194 = gtk_label_new_with_mnemonic (_("Actualis\303\251e"));
  gtk_widget_show (label194);
  gtk_box_pack_start (GTK_BOX (hbox62), label194, FALSE, FALSE, 0);

  spinbutton_fonction_agent_kh_adj = gtk_adjustment_new (1, 1, 2, 1, 10, 10);
  spinbutton_fonction_agent_kh = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_fonction_agent_kh_adj), 1, 0);
  gtk_widget_show (spinbutton_fonction_agent_kh);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_fonction_agent_kh, 344, 544);
  gtk_widget_set_size_request (spinbutton_fonction_agent_kh, 60, 27);

  type_tarif_label_kh = gtk_label_new (_("1-tarif parking \n\n2-securit\303\251 parking"));
  gtk_widget_show (type_tarif_label_kh);
  gtk_fixed_put (GTK_FIXED (fixed1), type_tarif_label_kh, 424, 528);
  gtk_widget_set_size_request (type_tarif_label_kh, 128, 48);

  afficher_par_fonction_kh_button = gtk_button_new ();
  gtk_widget_show (afficher_par_fonction_kh_button);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_par_fonction_kh_button, 288, 472);
  gtk_widget_set_size_request (afficher_par_fonction_kh_button, 200, 48);

  alignment63 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment63);
  gtk_container_add (GTK_CONTAINER (afficher_par_fonction_kh_button), alignment63);

  hbox63 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox63);
  gtk_container_add (GTK_CONTAINER (alignment63), hbox63);

  image76 = gtk_image_new_from_stock ("gtk-justify-right", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image76);
  gtk_box_pack_start (GTK_BOX (hbox63), image76, FALSE, FALSE, 0);

  label197 = gtk_label_new_with_mnemonic (_("Afficher par fonction"));
  gtk_widget_show (label197);
  gtk_box_pack_start (GTK_BOX (hbox63), label197, FALSE, FALSE, 0);

  non_trouve_label_home = gtk_label_new ("");
  gtk_widget_show (non_trouve_label_home);
  gtk_fixed_put (GTK_FIXED (fixed1), non_trouve_label_home, 672, 128);
  gtk_widget_set_size_request (non_trouve_label_home, 120, 88);

  g_signal_connect ((gpointer) treeviewnk, "row_activated",
                    G_CALLBACK (on_treeviewnk_row_iheb_activated),
                    NULL);
  g_signal_connect ((gpointer) Accueil_iheb_nav, "clicked",
                    G_CALLBACK (on_Accueil_iheb_nav_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_chercher_iheb, "clicked",
                    G_CALLBACK (on_btn_chercher_iheb_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_ajout_iheb, "clicked",
                    G_CALLBACK (on_btn_ajout_iheb_nav_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modifier_iheb_nav, "clicked",
                    G_CALLBACK (on_btn_modifier_iheb_nav_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_supprimer_iheb, "clicked",
                    G_CALLBACK (on_btn_supprimer_iheb_nav_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_reservation_iheb_nav, "clicked",
                    G_CALLBACK (on_btn_reservation_iheb_nav_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_actualise, "clicked",
                    G_CALLBACK (on_btn_actualise_iheb_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_par_fonction_kh_button, "clicked",
                    G_CALLBACK (on_afficher_par_fonction_kh_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ihebwindow, ihebwindow, "ihebwindow");
  GLADE_HOOKUP_OBJECT (ihebwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ihebwindow, treeviewnk, "treeviewnk");
  GLADE_HOOKUP_OBJECT (ihebwindow, entrychercheriheb, "entrychercheriheb");
  GLADE_HOOKUP_OBJECT (ihebwindow, Accueil_iheb_nav, "Accueil_iheb_nav");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (ihebwindow, image72, "image72");
  GLADE_HOOKUP_OBJECT (ihebwindow, label176, "label176");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_chercher_iheb, "btn_chercher_iheb");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (ihebwindow, image55, "image55");
  GLADE_HOOKUP_OBJECT (ihebwindow, label164, "label164");
  GLADE_HOOKUP_OBJECT (ihebwindow, label174, "label174");
  GLADE_HOOKUP_OBJECT (ihebwindow, label177, "label177");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_ajout_iheb, "btn_ajout_iheb");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ihebwindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (ihebwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_modifier_iheb_nav, "btn_modifier_iheb_nav");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ihebwindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (ihebwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_supprimer_iheb, "btn_supprimer_iheb");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ihebwindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (ihebwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_reservation_iheb_nav, "btn_reservation_iheb_nav");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment58, "alignment58");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (ihebwindow, image71, "image71");
  GLADE_HOOKUP_OBJECT (ihebwindow, label175, "label175");
  GLADE_HOOKUP_OBJECT (ihebwindow, btn_actualise, "btn_actualise");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment62, "alignment62");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (ihebwindow, image75, "image75");
  GLADE_HOOKUP_OBJECT (ihebwindow, label194, "label194");
  GLADE_HOOKUP_OBJECT (ihebwindow, spinbutton_fonction_agent_kh, "spinbutton_fonction_agent_kh");
  GLADE_HOOKUP_OBJECT (ihebwindow, type_tarif_label_kh, "type_tarif_label_kh");
  GLADE_HOOKUP_OBJECT (ihebwindow, afficher_par_fonction_kh_button, "afficher_par_fonction_kh_button");
  GLADE_HOOKUP_OBJECT (ihebwindow, alignment63, "alignment63");
  GLADE_HOOKUP_OBJECT (ihebwindow, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (ihebwindow, image76, "image76");
  GLADE_HOOKUP_OBJECT (ihebwindow, label197, "label197");
  GLADE_HOOKUP_OBJECT (ihebwindow, non_trouve_label_home, "non_trouve_label_home");

  return ihebwindow;
}

GtkWidget*
create_ajouteriheb (void)
{
  GtkWidget *ajouteriheb;
  GtkWidget *fixed1;
  GtkWidget *entry_id_agent;
  GtkWidget *entry_nom_agent;
  GtkWidget *entry_prenom_agent;
  GtkWidget *entry_numero_tel;
  GtkWidget *entry_id_parking;
  GtkWidget *entry_id_service;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *ajouter_iheb;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label9;
  GtkWidget *button_precedent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *radioiheb_h;
  GSList *radioiheb_h_group = NULL;
  GtkWidget *radioiheb_f;
  GtkWidget *label178;
  GtkWidget *comboboxentry_fonction1;

  ajouteriheb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouteriheb), _("ajouteriheb"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouteriheb), fixed1);

  entry_id_agent = gtk_entry_new ();
  gtk_widget_show (entry_id_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_agent, 264, 72);
  gtk_widget_set_size_request (entry_id_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_agent), 8226);

  entry_nom_agent = gtk_entry_new ();
  gtk_widget_show (entry_nom_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom_agent, 264, 128);
  gtk_widget_set_size_request (entry_nom_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_agent), 8226);

  entry_prenom_agent = gtk_entry_new ();
  gtk_widget_show (entry_prenom_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom_agent, 264, 184);
  gtk_widget_set_size_request (entry_prenom_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_agent), 8226);

  entry_numero_tel = gtk_entry_new ();
  gtk_widget_show (entry_numero_tel);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_numero_tel, 272, 344);
  gtk_widget_set_size_request (entry_numero_tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero_tel), 8226);

  entry_id_parking = gtk_entry_new ();
  gtk_widget_show (entry_id_parking);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_parking, 272, 392);
  gtk_widget_set_size_request (entry_id_parking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_parking), 8226);

  entry_id_service = gtk_entry_new ();
  gtk_widget_show (entry_id_service);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_service, 272, 448);
  gtk_widget_set_size_request (entry_id_service, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service), 8226);

  label1 = gtk_label_new (_("ID agent :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 136, 64);
  gtk_widget_set_size_request (label1, 120, 48);

  label2 = gtk_label_new (_("Nom agent :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 128, 120);
  gtk_widget_set_size_request (label2, 112, 40);

  label3 = gtk_label_new (_("Pr\303\251nom agent :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 104, 176);
  gtk_widget_set_size_request (label3, 152, 48);

  label4 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 176, 240);
  gtk_widget_set_size_request (label4, 72, 32);

  label5 = gtk_label_new (_("Fonction agent :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 112, 288);
  gtk_widget_set_size_request (label5, 136, 40);

  label6 = gtk_label_new (_("Numero tel :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 128, 344);
  gtk_widget_set_size_request (label6, 136, 32);

  label7 = gtk_label_new (_("ID parking :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 128, 392);
  gtk_widget_set_size_request (label7, 144, 32);

  label8 = gtk_label_new (_("ID service :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 144, 448);
  gtk_widget_set_size_request (label8, 120, 32);

  ajouter_iheb = gtk_button_new ();
  gtk_widget_show (ajouter_iheb);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_iheb, 536, 480);
  gtk_widget_set_size_request (ajouter_iheb, 136, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_iheb), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  button_precedent = gtk_button_new ();
  gtk_widget_show (button_precedent);
  gtk_fixed_put (GTK_FIXED (fixed1), button_precedent, 0, 0);
  gtk_widget_set_size_request (button_precedent, 128, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_precedent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("pr\303\251cedent"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  radioiheb_h = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radioiheb_h);
  gtk_fixed_put (GTK_FIXED (fixed1), radioiheb_h, 272, 232);
  gtk_widget_set_size_request (radioiheb_h, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioiheb_h), radioiheb_h_group);
  radioiheb_h_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioiheb_h));

  radioiheb_f = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radioiheb_f);
  gtk_fixed_put (GTK_FIXED (fixed1), radioiheb_f, 272, 264);
  gtk_widget_set_size_request (radioiheb_f, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioiheb_f), radioiheb_h_group);
  radioiheb_h_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioiheb_f));

  label178 = gtk_label_new (_("Ajouter agent "));
  gtk_widget_show (label178);
  gtk_fixed_put (GTK_FIXED (fixed1), label178, 216, 0);
  gtk_widget_set_size_request (label178, 264, 64);

  comboboxentry_fonction1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_fonction1);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentry_fonction1, 272, 296);
  gtk_widget_set_size_request (comboboxentry_fonction1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_fonction1), _("1-securite_parking"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_fonction1), _("2-tarif_parking"));

  g_signal_connect ((gpointer) ajouter_iheb, "clicked",
                    G_CALLBACK (on_ajouter_iheb_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent, "clicked",
                    G_CALLBACK (on_button_precedent_iheb_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioiheb_h, "toggled",
                    G_CALLBACK (on_radioiheb_h_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioiheb_f, "toggled",
                    G_CALLBACK (on_radioiheb_f_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouteriheb, ajouteriheb, "ajouteriheb");
  GLADE_HOOKUP_OBJECT (ajouteriheb, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_id_agent, "entry_id_agent");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_nom_agent, "entry_nom_agent");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_prenom_agent, "entry_prenom_agent");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_numero_tel, "entry_numero_tel");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_id_parking, "entry_id_parking");
  GLADE_HOOKUP_OBJECT (ajouteriheb, entry_id_service, "entry_id_service");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouteriheb, ajouter_iheb, "ajouter_iheb");
  GLADE_HOOKUP_OBJECT (ajouteriheb, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouteriheb, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouteriheb, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouteriheb, button_precedent, "button_precedent");
  GLADE_HOOKUP_OBJECT (ajouteriheb, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouteriheb, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouteriheb, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajouteriheb, radioiheb_h, "radioiheb_h");
  GLADE_HOOKUP_OBJECT (ajouteriheb, radioiheb_f, "radioiheb_f");
  GLADE_HOOKUP_OBJECT (ajouteriheb, label178, "label178");
  GLADE_HOOKUP_OBJECT (ajouteriheb, comboboxentry_fonction1, "comboboxentry_fonction1");

  return ajouteriheb;
}

GtkWidget*
create_modifieriheb (void)
{
  GtkWidget *modifieriheb;
  GtkWidget *fixed2;
  GtkWidget *entry_id_agent;
  GtkWidget *entry_nom_agent;
  GtkWidget *entry_prenom_agent;
  GtkWidget *entry_numero_tel;
  GtkWidget *entry_id_parking;
  GtkWidget *entry_id_service;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label21;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label17;
  GtkWidget *label11;
  GtkWidget *chercheriheb;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label18;
  GtkWidget *precedent_iheb_modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label19;
  GtkWidget *label_iheb_modif_out;
  GtkWidget *radioiheb_hm;
  GSList *radioiheb_hm_group = NULL;
  GtkWidget *radioiheb_fm;
  GtkWidget *label179;
  GtkWidget *modifier_iheb;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;
  GtkWidget *comboboxentry_fonction1;

  modifieriheb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifieriheb), _("modifieriheb"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifieriheb), fixed2);

  entry_id_agent = gtk_entry_new ();
  gtk_widget_show (entry_id_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id_agent, 160, 56);
  gtk_widget_set_size_request (entry_id_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_agent), 8226);

  entry_nom_agent = gtk_entry_new ();
  gtk_widget_show (entry_nom_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nom_agent, 160, 96);
  gtk_widget_set_size_request (entry_nom_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_agent), 8226);

  entry_prenom_agent = gtk_entry_new ();
  gtk_widget_show (entry_prenom_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_prenom_agent, 160, 136);
  gtk_widget_set_size_request (entry_prenom_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_agent), 8226);

  entry_numero_tel = gtk_entry_new ();
  gtk_widget_show (entry_numero_tel);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_numero_tel, 160, 288);
  gtk_widget_set_size_request (entry_numero_tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero_tel), 8226);

  entry_id_parking = gtk_entry_new ();
  gtk_widget_show (entry_id_parking);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id_parking, 160, 328);
  gtk_widget_set_size_request (entry_id_parking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_parking), 8226);

  entry_id_service = gtk_entry_new ();
  gtk_widget_show (entry_id_service);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id_service, 160, 368);
  gtk_widget_set_size_request (entry_id_service, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service), 8226);

  label15 = gtk_label_new (_("Numero tel :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 56, 280);
  gtk_widget_set_size_request (label15, 88, 40);

  label16 = gtk_label_new (_("Fonction agent :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 32, 248);
  gtk_widget_set_size_request (label16, 120, 32);

  label21 = gtk_label_new (_("Pr\303\251nom agent :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 40, 136);
  gtk_widget_set_size_request (label21, 104, 32);

  label14 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 80, 184);
  gtk_widget_set_size_request (label14, 80, 32);

  label13 = gtk_label_new (_("ID parking :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 56, 320);
  gtk_widget_set_size_request (label13, 96, 32);

  label12 = gtk_label_new (_("ID service :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 56, 368);
  gtk_widget_set_size_request (label12, 104, 32);

  label17 = gtk_label_new (_("Nom agent :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 64, 96);
  gtk_widget_set_size_request (label17, 80, 32);

  label11 = gtk_label_new (_("ID agent :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 64, 56);
  gtk_widget_set_size_request (label11, 96, 32);

  chercheriheb = gtk_button_new ();
  gtk_widget_show (chercheriheb);
  gtk_fixed_put (GTK_FIXED (fixed2), chercheriheb, 352, 56);
  gtk_widget_set_size_request (chercheriheb, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (chercheriheb), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  precedent_iheb_modifier = gtk_button_new ();
  gtk_widget_show (precedent_iheb_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), precedent_iheb_modifier, 0, 0);
  gtk_widget_set_size_request (precedent_iheb_modifier, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (precedent_iheb_modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  label_iheb_modif_out = gtk_label_new ("");
  gtk_widget_show (label_iheb_modif_out);
  gtk_fixed_put (GTK_FIXED (fixed2), label_iheb_modif_out, 344, 104);
  gtk_widget_set_size_request (label_iheb_modif_out, 120, 32);

  radioiheb_hm = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radioiheb_hm);
  gtk_fixed_put (GTK_FIXED (fixed2), radioiheb_hm, 168, 184);
  gtk_widget_set_size_request (radioiheb_hm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioiheb_hm), radioiheb_hm_group);
  radioiheb_hm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioiheb_hm));

  radioiheb_fm = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radioiheb_fm);
  gtk_fixed_put (GTK_FIXED (fixed2), radioiheb_fm, 168, 216);
  gtk_widget_set_size_request (radioiheb_fm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioiheb_fm), radioiheb_hm_group);
  radioiheb_hm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioiheb_fm));

  label179 = gtk_label_new (_("Modifier agent"));
  gtk_widget_show (label179);
  gtk_fixed_put (GTK_FIXED (fixed2), label179, 160, 16);
  gtk_widget_set_size_request (label179, 160, 32);

  modifier_iheb = gtk_button_new ();
  gtk_widget_show (modifier_iheb);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier_iheb, 376, 384);
  gtk_widget_set_size_request (modifier_iheb, 104, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (modifier_iheb), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  comboboxentry_fonction1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_fonction1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry_fonction1, 160, 248);
  gtk_widget_set_size_request (comboboxentry_fonction1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_fonction1), _("1-securit\303\251_parking"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_fonction1), _("2-tarif_parking"));

  g_signal_connect ((gpointer) chercheriheb, "clicked",
                    G_CALLBACK (on_chercheriheb_clicked),
                    NULL);
  g_signal_connect ((gpointer) precedent_iheb_modifier, "clicked",
                    G_CALLBACK (on_precedent_iheb_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioiheb_hm, "toggled",
                    G_CALLBACK (on_radioiheb_h_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioiheb_fm, "toggled",
                    G_CALLBACK (on_radioiheb_f_toggled),
                    NULL);
  g_signal_connect ((gpointer) modifier_iheb, "clicked",
                    G_CALLBACK (on_modifier_iheb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifieriheb, modifieriheb, "modifieriheb");
  GLADE_HOOKUP_OBJECT (modifieriheb, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_id_agent, "entry_id_agent");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_nom_agent, "entry_nom_agent");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_prenom_agent, "entry_prenom_agent");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_numero_tel, "entry_numero_tel");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_id_parking, "entry_id_parking");
  GLADE_HOOKUP_OBJECT (modifieriheb, entry_id_service, "entry_id_service");
  GLADE_HOOKUP_OBJECT (modifieriheb, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifieriheb, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifieriheb, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifieriheb, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifieriheb, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifieriheb, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifieriheb, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifieriheb, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifieriheb, chercheriheb, "chercheriheb");
  GLADE_HOOKUP_OBJECT (modifieriheb, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (modifieriheb, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modifieriheb, image3, "image3");
  GLADE_HOOKUP_OBJECT (modifieriheb, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifieriheb, precedent_iheb_modifier, "precedent_iheb_modifier");
  GLADE_HOOKUP_OBJECT (modifieriheb, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modifieriheb, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifieriheb, image4, "image4");
  GLADE_HOOKUP_OBJECT (modifieriheb, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifieriheb, label_iheb_modif_out, "label_iheb_modif_out");
  GLADE_HOOKUP_OBJECT (modifieriheb, radioiheb_hm, "radioiheb_hm");
  GLADE_HOOKUP_OBJECT (modifieriheb, radioiheb_fm, "radioiheb_fm");
  GLADE_HOOKUP_OBJECT (modifieriheb, label179, "label179");
  GLADE_HOOKUP_OBJECT (modifieriheb, modifier_iheb, "modifier_iheb");
  GLADE_HOOKUP_OBJECT (modifieriheb, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifieriheb, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifieriheb, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifieriheb, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifieriheb, comboboxentry_fonction1, "comboboxentry_fonction1");

  return modifieriheb;
}

GtkWidget*
create_supprimeriheb (void)
{
  GtkWidget *supprimeriheb;
  GtkWidget *fixed3;
  GtkWidget *entry_supp_iheb_id;
  GtkWidget *precedent_iheb_supp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label24;
  GtkWidget *label22;
  GtkWidget *confirmer_ihebsup;
  GtkWidget *label180;
  GtkWidget *supprimiheb;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label23;

  supprimeriheb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimeriheb), _("supprimeriheb"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (supprimeriheb), fixed3);
  gtk_widget_set_size_request (fixed3, 400, 400);

  entry_supp_iheb_id = gtk_entry_new ();
  gtk_widget_show (entry_supp_iheb_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_supp_iheb_id, 96, 168);
  gtk_widget_set_size_request (entry_supp_iheb_id, 140, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_supp_iheb_id), 8226);

  precedent_iheb_supp = gtk_button_new ();
  gtk_widget_show (precedent_iheb_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), precedent_iheb_supp, 0, 0);
  gtk_widget_set_size_request (precedent_iheb_supp, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (precedent_iheb_supp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox7), label24, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("ID :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 32, 168);
  gtk_widget_set_size_request (label22, 72, 32);

  confirmer_ihebsup = gtk_check_button_new_with_mnemonic (_("Etes vous sure ?"));
  gtk_widget_show (confirmer_ihebsup);
  gtk_fixed_put (GTK_FIXED (fixed3), confirmer_ihebsup, 104, 224);
  gtk_widget_set_size_request (confirmer_ihebsup, 168, 24);

  label180 = gtk_label_new (_("Supprimer agent "));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed3), label180, 96, 96);
  gtk_widget_set_size_request (label180, 176, 40);

  supprimiheb = gtk_button_new ();
  gtk_widget_show (supprimiheb);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimiheb, 264, 168);
  gtk_widget_set_size_request (supprimiheb, 104, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (supprimiheb), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox6), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) precedent_iheb_supp, "clicked",
                    G_CALLBACK (on_precedent_iheb_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_ihebsup, "toggled",
                    G_CALLBACK (on_confirmer_ihebsup_toggled),
                    NULL);
  g_signal_connect ((gpointer) supprimiheb, "clicked",
                    G_CALLBACK (on_supprimiheb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimeriheb, supprimeriheb, "supprimeriheb");
  GLADE_HOOKUP_OBJECT (supprimeriheb, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimeriheb, entry_supp_iheb_id, "entry_supp_iheb_id");
  GLADE_HOOKUP_OBJECT (supprimeriheb, precedent_iheb_supp, "precedent_iheb_supp");
  GLADE_HOOKUP_OBJECT (supprimeriheb, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (supprimeriheb, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (supprimeriheb, image7, "image7");
  GLADE_HOOKUP_OBJECT (supprimeriheb, label24, "label24");
  GLADE_HOOKUP_OBJECT (supprimeriheb, label22, "label22");
  GLADE_HOOKUP_OBJECT (supprimeriheb, confirmer_ihebsup, "confirmer_ihebsup");
  GLADE_HOOKUP_OBJECT (supprimeriheb, label180, "label180");
  GLADE_HOOKUP_OBJECT (supprimeriheb, supprimiheb, "supprimiheb");
  GLADE_HOOKUP_OBJECT (supprimeriheb, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (supprimeriheb, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (supprimeriheb, image6, "image6");
  GLADE_HOOKUP_OBJECT (supprimeriheb, label23, "label23");

  return supprimeriheb;
}

GtkWidget*
create_reserveriheb (void)
{
  GtkWidget *reserveriheb;
  GtkWidget *fixed4;
  GtkWidget *treeview_reservation_ik;
  GtkWidget *button_precedent_iheb_reservation;
  GtkWidget *alignment60;
  GtkWidget *hbox60;
  GtkWidget *image73;
  GtkWidget *label191;
  GtkWidget *calander_resrver_iheb;
  GtkWidget *label192;
  GtkWidget *label195;
  GtkWidget *afficher_res_par_date_ik;
  GtkWidget *alignment64;
  GtkWidget *hbox64;
  GtkWidget *image77;
  GtkWidget *label198;

  reserveriheb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (reserveriheb, 762, 416);
  gtk_window_set_title (GTK_WINDOW (reserveriheb), _("reserveriheb"));
  gtk_window_set_default_size (GTK_WINDOW (reserveriheb), 800, 500);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (reserveriheb), fixed4);

  treeview_reservation_ik = gtk_tree_view_new ();
  gtk_widget_show (treeview_reservation_ik);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_reservation_ik, 48, 104);
  gtk_widget_set_size_request (treeview_reservation_ik, 536, 312);

  button_precedent_iheb_reservation = gtk_button_new ();
  gtk_widget_show (button_precedent_iheb_reservation);
  gtk_fixed_put (GTK_FIXED (fixed4), button_precedent_iheb_reservation, 0, 0);
  gtk_widget_set_size_request (button_precedent_iheb_reservation, 112, 48);

  alignment60 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment60);
  gtk_container_add (GTK_CONTAINER (button_precedent_iheb_reservation), alignment60);

  hbox60 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox60);
  gtk_container_add (GTK_CONTAINER (alignment60), hbox60);

  image73 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image73);
  gtk_box_pack_start (GTK_BOX (hbox60), image73, FALSE, FALSE, 0);

  label191 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label191);
  gtk_box_pack_start (GTK_BOX (hbox60), label191, FALSE, FALSE, 0);

  calander_resrver_iheb = gtk_calendar_new ();
  gtk_widget_show (calander_resrver_iheb);
  gtk_fixed_put (GTK_FIXED (fixed4), calander_resrver_iheb, 600, 120);
  gtk_widget_set_size_request (calander_resrver_iheb, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calander_resrver_iheb),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label192 = gtk_label_new (_("Afficher reservation par date "));
  gtk_widget_show (label192);
  gtk_fixed_put (GTK_FIXED (fixed4), label192, 96, 40);
  gtk_widget_set_size_request (label192, 312, 64);

  label195 = gtk_label_new (_("Choisir une date "));
  gtk_widget_show (label195);
  gtk_fixed_put (GTK_FIXED (fixed4), label195, 608, 80);
  gtk_widget_set_size_request (label195, 144, 32);

  afficher_res_par_date_ik = gtk_button_new ();
  gtk_widget_show (afficher_res_par_date_ik);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher_res_par_date_ik, 608, 320);
  gtk_widget_set_size_request (afficher_res_par_date_ik, 152, 56);
  gtk_container_set_border_width (GTK_CONTAINER (afficher_res_par_date_ik), 3);

  alignment64 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment64);
  gtk_container_add (GTK_CONTAINER (afficher_res_par_date_ik), alignment64);

  hbox64 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox64);
  gtk_container_add (GTK_CONTAINER (alignment64), hbox64);

  image77 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image77);
  gtk_box_pack_start (GTK_BOX (hbox64), image77, FALSE, FALSE, 0);

  label198 = gtk_label_new_with_mnemonic (_("Afficher par date"));
  gtk_widget_show (label198);
  gtk_box_pack_start (GTK_BOX (hbox64), label198, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_precedent_iheb_reservation, "clicked",
                    G_CALLBACK (on_button_precedent_iheb_reservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) calander_resrver_iheb, "day_selected_double_click",
                    G_CALLBACK (on_calander_resrver_iheb_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) calander_resrver_iheb, "day_selected",
                    G_CALLBACK (on_calander_resrver_iheb_day_selected),
                    NULL);
  g_signal_connect ((gpointer) afficher_res_par_date_ik, "clicked",
                    G_CALLBACK (on_afficher_res_par_date_ik_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reserveriheb, reserveriheb, "reserveriheb");
  GLADE_HOOKUP_OBJECT (reserveriheb, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (reserveriheb, treeview_reservation_ik, "treeview_reservation_ik");
  GLADE_HOOKUP_OBJECT (reserveriheb, button_precedent_iheb_reservation, "button_precedent_iheb_reservation");
  GLADE_HOOKUP_OBJECT (reserveriheb, alignment60, "alignment60");
  GLADE_HOOKUP_OBJECT (reserveriheb, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (reserveriheb, image73, "image73");
  GLADE_HOOKUP_OBJECT (reserveriheb, label191, "label191");
  GLADE_HOOKUP_OBJECT (reserveriheb, calander_resrver_iheb, "calander_resrver_iheb");
  GLADE_HOOKUP_OBJECT (reserveriheb, label192, "label192");
  GLADE_HOOKUP_OBJECT (reserveriheb, label195, "label195");
  GLADE_HOOKUP_OBJECT (reserveriheb, afficher_res_par_date_ik, "afficher_res_par_date_ik");
  GLADE_HOOKUP_OBJECT (reserveriheb, alignment64, "alignment64");
  GLADE_HOOKUP_OBJECT (reserveriheb, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (reserveriheb, image77, "image77");
  GLADE_HOOKUP_OBJECT (reserveriheb, label198, "label198");

  return reserveriheb;
}

